[camera]
far = 100.0
fov = 75.0
front = [ 0.23271548748016357, -0.29721301794052124, 0.92601722478866577 ]
near = 0.10000000000000001
position = [ -0.39754316210746765, 1.7606989145278931, -2.848052978515625 ]

[cubemap]
back = 'assets/cubemap/back.jpg'
bottom = 'assets/cubemap/bottom.jpg'
front = 'assets/cubemap/front.jpg'
left = 'assets/cubemap/left.jpg'
right = 'assets/cubemap/right.jpg'
top = 'assets/cubemap/top.jpg'

[display]
height = 1080
refreshrate = 144
vsync = true
width = 1920

[entity]
configfile = 'assets/config/entity.json'
fragmentshaderfile = 'assets/shaders/shaderEntity.frag'
vertexshaderfile = 'assets/shaders/shaderEntity.vert'