[camera]
far = 100.0
fov = 75.0
front = [ -0.25090724229812622, 0.14953534305095673, 0.95639151334762573 ]
near = 0.10000000000000001
position = [ 3.6833419799804688, 6.119898796081543, -12.860110282897949 ]

[cubemap]
back = 'assets/cubemap/back.jpg'
bottom = 'assets/cubemap/bottom.jpg'
front = 'assets/cubemap/front.jpg'
left = 'assets/cubemap/left.jpg'
right = 'assets/cubemap/right.jpg'
top = 'assets/cubemap/top.jpg'

[display]
height = 1080
refreshrate = 144
vsync = true
width = 1920

[entity]
configfile = 'assets/config/entity.json'
fragmentshaderfile = 'assets/shaders/shaderEntity.frag'
vertexshaderfile = 'assets/shaders/shaderEntity.vert'