[camera]
far = 100.0
fov = 75.0
front = [ -0.66931909322738647, -0.2084583044052124, -0.71313190460205078 ]
near = 0.10000000000000001
position = [ 3.0202867984771729, 4.0228219032287598, 5.9664463996887207 ]

[cubemap]
back = 'assets/cubemap/back.jpg'
bottom = 'assets/cubemap/bottom.jpg'
front = 'assets/cubemap/front.jpg'
left = 'assets/cubemap/left.jpg'
right = 'assets/cubemap/right.jpg'
top = 'assets/cubemap/top.jpg'

[display]
height = 1080
refreshrate = 144
vsync = true
width = 1920

[entity]
configfile = 'assets/config/entity.json'
fragmentshaderfile = 'assets/shaders/shaderEntity.frag'
vertexshaderfile = 'assets/shaders/shaderEntity.vert'