[[entity]]
ID = 0
path = 'assets/models/statue-chiriqui-3d-model/scene.gltf'
scale = 4.0560002326965332

    [entity.position]
    x = 15.217000007629395
    y = 0.0
    z = 0.0

    [entity.rotation]
    x = -57.390998840332031
    y = 0.0
    z = 0.0

[[entity]]
ID = 1
path = 'assets/models/statue-chiriqui-3d-model/scene.gltf'
scale = 2.0

    [entity.position]
    x = 0.0
    y = 0.0
    z = 0.0

    [entity.rotation]
    x = 0.0
    y = 0.0
    z = 0.0